[package]
name = "runnable"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[dependencies]
gpui.workspace = true
settings.workspace = true
util.workspace = true
anyhow.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
parking_lot.workspace = true
smol.workspace = true

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
