[package]
name = "runnable"
version = "0.1.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"

[dependencies]
gpui = { path = "../gpui" }
settings = { path = "../settings" }
util = { path = "../util" }
anyhow.workspace = true
futures.workspace = true
serde.workspace = true
serde_json = "1.0.113"
async-process = "2.0.1"
postage = "0.5"
parking_lot.workspace = true
smol.workspace = true

[dev-dependencies]
gpui = { path = "../gpui", features = ["test-support"] }
