[package]
name = "runnables_panel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
editor.workspace = true
fs.workspace = true
gpui.workspace = true
project.workspace = true
runnable.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json = "1.0.113"
settings.workspace = true
theme.workspace = true
ui.workspace = true
workspace.workspace = true
