[package]
name = "runnables_panel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpui = { path = "../gpui" }
project = { path = "../project" }
runnable = { path = "../runnable" }
schemars.workspace = true
serde.workspace = true
serde_json = "1.0.113"
settings = { path = "../settings" }
ui = { path = "../ui" }
workspace = { path = "../workspace" }
